# Generated by Django 3.2.6 on 2021-10-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_level_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='length',
        ),
        migrations.AddField(
            model_name='class',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
