# Generated by Django 3.2.6 on 2021-09-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('artist_statement', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
