# Generated by Django 3.2.6 on 2021-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20210926_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='fb_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='ig_url',
            new_name='instagram_url',
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
